Added effect bug to README
akashic-games/akashic-animation pull request #56
Opened 2021-03-18 02:18 UTC by ShinobuTakahashi

## 概要

エフェクト機能が不具合により利用できない旨を README へ記述します。

2021-03-18 03:12 UTC, xnv requested changes

2021-03-18 03:12 UTC, xnv commented on README.md
> +**現バージョンでは、不具合によりエフェクト機能が利用できません。**
ここでだと目立ちすぎる (割に何をどうすればいいのか読み取れない) ので、サンプルの README の方に「現状不具合のためこのサンプルは動作していません」と記述したいです。

2021-03-18 03:20 UTC, ShinobuTakahashi commented on README.md
> +**現バージョンでは、不具合によりエフェクト機能が利用できません。**
サンプル Effect の README に記述するよう修正しました。

2021-03-19 03:04 UTC, xnv approved these changes

2021-03-19 03:05 UTC, merged